name: Deploy to Azure with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: change
        uses: cschleiden/replace-tokens@v1.2
        with:
          tokenPrefix: "#{"
          tokenSuffix: "}#"
          files: '[ "./**/*.{tf,yaml,yml}" ]'
        env:
          AZURE_TENANT_ID:  ${{ secrets.AZURE_TENANT_ID }}
          STORAGE_KEY: ${{ secrets.STORAGE_KEY }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Setup Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: List directory
        run: ls -a

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan 

      - name: Deploy if approved
        run: terraform apply -auto-approve 
