name: Deploy to Azure with Terraform

on:
  push:
    branches:
      - main

permissions:
    issues: write
    id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
    steps:
      - name: Clone Github Repo Action
        uses: actions/checkout@v4

      - name: ping azure
        run: cat /etc/resolv.conf; ping portal.azure.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: List directory
        run: ls -a

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan 

      - name: Deploy if approved
        run: terraform apply -auto-approve 
