name: Deploy to Azure with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
<<<<<<< HEAD
        uses: hashicorp/setup-terraform@v2


      - name: Setup Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

=======
        uses: hashicorp/setup-terraform@v1
      - name: Setup Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
>>>>>>> 42dc360152572733198ce1f2532df4bba4790c50
      - name: List directory
        run: ls -a

      - name: Terraform Init
<<<<<<< HEAD
        run: terraform init
=======
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan 

      - name: Deploy if approved
        run: terraform apply -auto-approve 
>>>>>>> 42dc360152572733198ce1f2532df4bba4790c50
