name: Deploy to Azure with Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Injection du nom de demain
        run: sudo rm -f /etc/resolv.conf; sudo echo "nameserver 8.8.8.8" >>/etc/resolv.conf

      - name: ping azure
        run: cat /etc/resolv.conf; ping portal.azure.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Setup Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: List directory
        run: ls -a

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan 

      - name: Deploy if approved
        run: terraform apply -auto-approve 
